services:
  we-bot:
    container_name: we-bot
    restart: always
    build: .
    expose:
      - "3006"
    env_file:
      - .env
    networks:
      - red_publica
    dns:
      - 8.8.8.8
      - 1.1.1.1

networks:
  red_publica:
    external: true
